#+title: MAD5939-03 ACM Computing Seminar – Fall 20119
#+name: Zhifeng Deng
#+options: html-postamble:nil toc:nil name:nil
#+options: H:1 num:0
#+html_head: <link rel="stylesheet" type="text/css" href="css/main.css">
#+html: <div id="main">

* Course Information 

| *Time & Place:* | Monday 18:45-20:00, LOV 102                       |
| *Instructor:*   | Zhifeng Deng                                      |
| *Office Hours:* | Monday/Tuesday 1:00-2:30 or by appointment        |
| *Email:*        | [[mailto:zdeng@math.fsu.edu?subject=MAT5939 ... ][zdeng@math.fsu.edu]]                                |
| *Website:*      | [[./][www.math.fsu.edu/~zdeng/acm-computing-seminar/]]    |

* Course Objectives

To learn the C++ programming langauge with a focus on  mathematical 
and scientific programming applications.

* Prerequisites

Graduate standing in mathematics.

* Course Outline

1. Getting started
   + compilers, editors
   + writing a simple program
2. Data types
   + common data types, casting, arrays, etc.
3. Control Structures
   + conditionals
   + structures for iterating
4. Input and output
   + arguments from the command line
   + reading and writing to files
5. Functions
   + writing functions
   + modularizing code with header and implementation files
   + function pointers
6. Object-oriented programming
   + basics of writing classes: constructors, destructors, operator overloading, etc.

* Grade Policy:

Homework will be assigned biweekly, 5 in total. They are simple routines that have
nontrivial behaviors under certain aspects, e.g., accuracy, complexity and/or data 
structure. You are expected to implement the routines, run experiments to expolit
the features and collect, present and discuss your result systematically in documents. 

Beside the biweekly homework, there is a comprehensive program assignment. You will
work on a more complicated problems that involves sophisticated experimental design.
The report of this comprehensive program will be graded at the same level of FCM's
programs.


You only need to do either 5 homework or 1 comprehensive program. The comprehensive
program is for those who have mastered certain programming skills. If your program
report meets the requirement, you are consider qualified for both this seminar and
FCM's programming prerequisities. 

Homework is graded on a 0 – 3 scale:

    + 0 - no result submitted or code copied from another source
    + 1 - result submitted, but did not demonstrate code functions properly
    + 2 - showed code functions properly, but results not fully explained
    + 3 - showed code functions properly, presented results clearly and fully

Program is graded on a 0 - 100 scale which is the same as normal FCM program.

To earn a grade of S, you must have final grade greater or equal to 2 for homework or 70 for comprehensive program. 

For each homework or program assignment you will email me a report with your source code in the required format.

For some program assignments, you may be expected to come to my office and run it.

* Homework Policy

You must convince me your code functions as required. It is up to you to 
consider sufficient test cases, although I will provide guidance and more 
examples of what this means in the first couple of assignments. The reports 
should be considerably less detailed than those submitted for FCM. For example, 
there is no need for a "Description of Mathematics" or 
"Decription of Algorithm"; rather, an explanation of why you chose the 
test cases and any special programming methods/data structures you decided 
to use to solve the problem will be sufficient.
 
* Attendance Policy

Excused absences include documented illness, deaths in the family and other 
documented crises, call to active military duty or jury duty, religious holy 
days, and official University activities. These absences will be accommodated 
in a way that does not arbitrarily penalize students who have a valid excuse. 
Consideration will also be given to students whose dependent children 
experience serious illness.

* Academic Honor Policy

The Florida State University Academic Honor Policy outlines the University’s 
expectations for the integrity of students’ academic work, the procedures for 
resolving alleged violations of those expectations, and the rights and 
responsibilities of students and faculty members throughout the process. 
Students are responsible for reading the Academic Honor Policy and for living 
up to their pledge to “... be honest and truthful and ... [to] strive for 
personal and institutional integrity at Florida State University.” 

(Florida State University Academic Honor Policy, found at
http://fda.fsu.edu/Academics/Academic-Honor-Policy.)

* Americans with Disabilities

Students with disabilities needing academic accommodation should:

1. Register with and provide documentation to the Student Disability Resource Center
2. Bring a letter to the instructor indicating the need for accommodation and what type. This should be done

during the first week of class.

This syllabus and other class materials are available in alternative format 
upon request. For more information about services available to FSU students 
with disabilities, contact the:

Student Disability Resource Center
874 Traditions Way
108 Student Services Building
Florida State University
Tallahassee, FL 32306-4167
(850) 644-9566 (voice)
(850) 644-8504 (TDD)

sdrc@admin.fsu.edu
http://www.disabilitycenter.fsu.edu/

* Syllabus Change Policy

Except for changes that substantially affect implementation of the evaluation (grading)
statement, this syllabus is a guide for the course and is subject to change with advance notice.


#+html: <div id="main">

